{
    'name': 'Localiza SRM CRM Integrado',
    'version': '19.0.4.0.0',
    'category': 'Sales/CRM',
    'summary': 'Extiende el CRM nativo de Odoo con ficha Localiza, eventos/tareas, actividades, historial de fases, controles anti-duplicados y reportes.',
    'author': 'XIM Power / Localiza',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'crm', 'calendar', 'sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'views/sequence.xml',
        'views/crm_stage_history_views.xml',
        'views/crm_lead_views.xml',
        'views/res_partner_views.xml',
        'views/mail_activity_views.xml',
        'views/calendar_event_views.xml',
        'views/sale_order_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
}
