{
    'name': 'Localiza Bodega Operativa',
    'version': '19.0.1.0.0',
    'summary': 'Control operativo de bodega, puestos, asignaciones, GPS e importaciones Excel',
    'description': 'Modulo robusto y simple para inventario operativo inspirado en Localiza: productos, asignaciones, puestos, GPS, importaciones y tablero analitico.',
    'author': 'XIM Power / Localiza',
    'website': 'https://ximpower.com',
    'category': 'Inventory/Inventory',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'stock', 'mail', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/dashboard.xml',
        'views/product_views.xml',
        'views/localiza_puesto_views.xml',
        'views/localiza_articulo_views.xml',
        'views/localiza_gps_views.xml',
        'views/localiza_asignacion_views.xml',
        'views/localiza_importacion_views.xml',
        'views/localiza_dashboard_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
